### ISSUE TITLE
Heroku Dashboard

### ISSUE THREAD

**Issue by charliewilco** [EmberSherpa/open-source-ember-apps#18]
Heroku's dashboard is using Ember 2.5.1

<img width="1197" alt="screenshot 2016-08-17 01 39 10" src="https://cloud.githubusercontent.com/assets/4588060/17729996/8e2632ac-641b-11e6-87f0-c4b1246ea674.png">

**Comment by taras** [comment]
PR welcome my friend!

**Comment by charliewilco** [comment]
added!
