### ISSUE TITLE
How to add Lisweb Frontend to the List?

### ISSUE THREAD

**Issue by wellington1993** [EmberSherpa/open-source-ember-apps#56]
Hi,

I want to add that project to the list:
https://github.com/hotsoft-informatica/lisweb_frontend

How to proceed?

Thanks!

**Comment by wellington1993** [comment]
I tried via Pull Request:
https://github.com/EmberSherpa/open-source-ember-apps/pull/57

**Comment by zinyando** [comment]
A PR is the best way, I've merged it. Thanks.
